version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "hourly"
    open-pull-requests-limit: 2
    allow:
      - dependency-name: "poe-api"
        update-type: "waste"
