version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: main
    assignees:
      - thelime1
    versioning-strategy: increase
    commit-message:
      prefix: "build"
# Remove the following props to fix errors
#    pull-request-body: |
#      This PR updates the `poe-api` package to the latest version.
#    label:
#      - "pip updates"
#    update-schedule: "live"
