version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "poe-api"
        update-type: "all"
        version-range: ">=0.2.10"
