version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "all"
    dependency-ecosystem: "pip"
    update:
      - package-regex: "^poe-api$"
        directory: "/"
        schedule:
          interval: "daily"
        versioning: "widen"
        commit-message: "chore(deps): bump poe-api from {{oldVersion}} to {{newVersion}}"
        labels:
          - "dependencies"
        reviewers:
          - "thelime1"
        assignees:
          - "thelime1"
        branch-name: "dependabot/pip/poe-api-{{newVersion}}"
        author-email: "everpadd4@gmail.com"
        author-name: "Aymen Hmani"
        pr-title: "Update poe-api to {{newVersion}}"
